# SwiftLint Configuration
# https://github.com/realm/SwiftLint

disabled_rules:
  - trailing_whitespace
  - line_length

opt_in_rules:
  - empty_count
  - closure_spacing
  - contains_over_first_not_nil
  - fatal_error_message
  - first_where
  - force_unwrapping
  - modifier_order
  - nimble_operator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces

included:
  - TextToBand
  - TextToBandTests
  - TextToBandUITests

excluded:
  - TextToBand.xcodeproj
  - DerivedData
  - Build

# Rules configuration
file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 300
  error: 500

cyclomatic_complexity:
  warning: 10
  error: 20

identifier_name:
  min_length: 1
  max_length: 40
  excluded:
    - id
    - x
    - y

large_tuple:
  warning: 3
  error: 4
