# SwiftLint Configuration
# https://github.com/realm/SwiftLint

disabled_rules:
  - trailing_whitespace
  - line_length
  - force_unwrapping
  - force_try
  - redundant_string_enum_value
  - type_body_length
  - function_body_length

opt_in_rules:
  - empty_count
  - closure_spacing
  - contains_over_first_not_nil
  - modifier_order
  - object_literal
  - operator_usage_whitespace
  - redundant_nil_coalescing
  - sorted_first_last
  - unneeded_parentheses_in_closure_argument

included:
  - TextToBand

excluded:
  - TextToBand.xcodeproj
  - DerivedData
  - Build
  - TextToBandTests
  - TextToBandUITests

# Rules configuration
file_length:
  warning: 800
  error: 1200

cyclomatic_complexity:
  warning: 15
  error: 25

identifier_name:
  min_length: 1
  max_length: 50
  excluded:
    - id
    - x
    - y

large_tuple:
  warning: 4
  error: 6
