name: 🐛 Bug Report
description: Сообщить об ошибке или неожиданном поведении
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Спасибо за сообщение об ошибке! Заполните форму ниже, чтобы помочь нам исправить проблему.

  - type: textarea
    id: description
    attributes:
      label: 📝 Описание ошибки
      description: Краткое и понятное описание проблемы
      placeholder: Опишите, что произошло...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 🔄 Шаги для воспроизведения
      description: Пошаговые инструкции для воспроизведения ошибки
      placeholder: |
        1. Перейти к '...'
        2. Нажать на '...'
        3. Прокрутить до '...'
        4. Увидеть ошибку
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: ✅ Ожидаемое поведение
      description: Что должно было произойти
      placeholder: Опишите ожидаемое поведение...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: ❌ Фактическое поведение
      description: Что произошло на самом деле
      placeholder: Опишите фактическое поведение...
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: 📸 Скриншоты
      description: Если применимо, добавьте скриншоты для объяснения проблемы
      placeholder: Вставьте скриншоты здесь...

  - type: dropdown
    id: device
    attributes:
      label: 📱 Устройство
      description: На каком устройстве возникла проблема?
      options:
        - iPhone 16 Pro Max
        - iPhone 16 Pro
        - iPhone 16 Plus
        - iPhone 16
        - iPhone 15 Pro Max
        - iPhone 15 Pro
        - iPhone 15 Plus
        - iPhone 15
        - iPhone 14 Pro Max
        - iPhone 14 Pro
        - iPhone 14 Plus
        - iPhone 14
        - iPad Pro
        - iPad Air
        - iPad mini
        - iPad
        - Симулятор
        - Другое
    validations:
      required: true

  - type: dropdown
    id: ios-version
    attributes:
      label: 📱 Версия iOS
      description: Какая версия iOS используется?
      options:
        - iOS 18.5
        - iOS 18.4
        - iOS 18.3
        - iOS 18.2
        - iOS 18.1
        - iOS 18.0
        - Другая
    validations:
      required: true

  - type: input
    id: app-version
    attributes:
      label: 📦 Версия приложения
      description: Какая версия TextToBand используется?
      placeholder: "например, 1.0.0"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: 📋 Дополнительная информация
      description: Любая другая информация, которая может помочь в решении проблемы
      placeholder: Добавьте любую дополнительную информацию...

  - type: checkboxes
    id: terms
    attributes:
      label: ✅ Чеклист
      description: Убедитесь, что вы выполнили следующие пункты
      options:
        - label: Я искал похожие issues и не нашел дубликатов
          required: true
        - label: Я использую последнюю версию приложения
          required: true
        - label: Я предоставил всю необходимую информацию
          required: true
